from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from morphtamp_x_v2.morphology import ARM_DESIGNS, ARM_DESIGN_TYPES  # noqa: E402
from morphtamp_x_v2.objects import OBJECT_SPECS, OBJECT_TYPES  # noqa: E402
from morphtamp_x_v2.tasks import TASK_SPECS, TASK_TYPES  # noqa: E402
from morphtamp_x_v2.cli import parser as cli_parser  # noqa: E402


PANDA_XML = "~/robocasa/mujoco_menagerie/franka_emika_panda/scene.xml"


def _object_table() -> str:
    rows = [
        "| Object | Geometry | Size | Description |",
        "|---|---:|---:|---|",
    ]
    for name in OBJECT_TYPES:
        spec = OBJECT_SPECS[name]
        size = ", ".join(f"{value:g}" for value in spec.size)
        rows.append(f"| `{name}` | `{spec.geom_type}` | `{size}` | {spec.description} |")
    return "\n".join(rows)


def _task_table() -> str:
    rows = [
        "| Task | Start xy | Target xy | Obstacle | Motion style | Description |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for name in TASK_TYPES:
        spec = TASK_SPECS[name]
        obstacle = "yes" if spec.obstacle_center is not None else "no"
        rows.append(
            f"| `{name}` | `{spec.start_xy}` | `{spec.target_xy}` | {obstacle} | "
            f"`{spec.motion_style}` | {spec.description} |"
        )
    return "\n".join(rows)


def _design_table() -> str:
    rows = [
        "| Design | Upper | Forearm | Wrist | Base shift | Description |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for name in ARM_DESIGN_TYPES:
        design = ARM_DESIGNS[name]
        rows.append(
            f"| `{name}` | {design.upper_scale:g} | {design.forearm_scale:g} | "
            f"{design.wrist_scale:g} | {design.base_shift} | {design.description} |"
        )
    return "\n".join(rows)


def _cli_command_table() -> str:
    root = cli_parser()
    subparsers = next(
        action for action in root._actions
        if getattr(action, "dest", None) == "command"
    )
    descriptions = {
        "list-objects": "print available object types",
        "list-tasks": "print available task types",
        "check-tasks": "validate object/task library geometry",
        "plan": "generate symbolic pick-place phases",
        "build-scene": "write a MuJoCo Panda/object/task scene XML",
        "run": "select a grasp, build scene, solve Panda replay, and write replay JSON",
        "view": "open or report a generated replay",
        "browse": "interactive object/task switching viewer",
        "validate-physics": "run replay-level physics validation",
        "benchmark": "evaluate object/task combinations",
        "compare-grasps": "rank grasp candidates and generate per-candidate replays",
        "browse-candidates": "interactive switching viewer for grasp candidates",
        "analyze-benchmark": "summarize benchmark JSON to JSON/CSV/Markdown",
        "morphology-benchmark": "evaluate morphology designs over object/task cases",
        "optimize-morphology": "search continuous morphology scales for lowest feasible cost",
        "robustness-benchmark": "evaluate seed/pose perturbation robustness",
        "failure-analysis": "summarize failed cases by design, object, task, and reason",
        "design-analysis": "generate Pareto, segment-importance, and recommendation reports",
        "visualize-results": "generate benchmark and morphology figures",
    }
    rows = [
        "| Command | Purpose |",
        "|---|---|",
    ]
    for command in sorted(subparsers.choices):
        rows.append(f"| `{command}` | {descriptions.get(command, 'CLI command')} |")
    return "\n".join(rows)


def build_readme() -> str:
    return f"""# Cube MorphTAMP-X v2

<!-- AUTO-GENERATED by tools/update_readme.py. Do not edit generated sections by hand. -->

Cube MorphTAMP-X v2 is the clean MuJoCo / Franka Panda prototype for your current
research direction: task-aware arm morphology optimization with object-specific
grasp planning, reachability, singularity-aware IK evidence, collision checks,
and visual replay.

The project is intentionally separate from the older `reachability_morphology_lab`
prototype. Treat this folder as the current baseline.

## What this project does

The closed loop is:

1. choose an object and task scene;
2. generate multiple grasp candidates for that object;
3. score candidates using IK error, orientation error, joint margin, collision,
   7D joint path length, max joint step, and condition number;
4. replay the selected plan with a real 7-DOF Franka/Panda MuJoCo model;
5. optionally compare all grasp candidates in a report and switch between their
   individual replays;
6. run object-task and morphology benchmarks for cost / reachability tradeoffs.

Evidence scope: this is a research prototype for reachability, kinematic
feasibility, grasp-candidate selection, collision-aware replay, and morphology
cost comparison. It is not yet a full force-controlled contact manipulation stack.

## Simulation snapshots

These screenshots are generated from MuJoCo replay scenes with the Franka/Panda
model and object-specific grasp planning. Regenerate them with
`python tools/render_readme_screenshots.py --panda-xml {PANDA_XML}`.

| Cube over barrier | Sphere folded transfer | Plate shelf place |
|---|---|---|
| ![Cube transfer over a solid obstacle](docs/assets/readme/cube_over_barrier.png) | ![Sphere folded transfer task](docs/assets/readme/sphere_folded_transfer.png) | ![Plate shelf placement task](docs/assets/readme/plate_shelf_place.png) |
| Solid-obstacle transfer with selected Panda replay. | Folded arm posture while carrying a sphere. | Object-specific grasp selection for plate-style placement. |

## Environment

From WSL:

```bash
cd ~/robocasa/cube_morphtamp_x_v2
conda activate robocasa
export PYTHONPATH=src:tools
```

Recommended Franka/Panda model:

```bash
{PANDA_XML}
```

If you open an interactive viewer, use:

```bash
MUJOCO_GL=glfw
```

## Keep this README updated

This README is generated from the code registries for objects, tasks, and arm
designs. After changing CLI behavior, object definitions, task definitions, or
morphology presets, run:

```bash
python tools/update_readme.py
python -m pytest -q tests/test_readme_sync.py
```

The test fails if `README.md` is stale, so normal test runs will remind you to
regenerate it after code changes.

## Quick health check

```bash
python -m pytest -q tests

python -m morphtamp_x_v2.cli list-objects
python -m morphtamp_x_v2.cli list-tasks
python -m morphtamp_x_v2.cli check-tasks
```

## CLI command reference

{_cli_command_table()}

## Single task run

Generate one selected plan and replay:

```bash
python -m morphtamp_x_v2.cli run \\
  --object cube \\
  --task over_barrier \\
  --panda-xml {PANDA_XML} \\
  --auto-fit-panda \\
  --position-tolerance 0.035 \\
  --full-candidate-limit 2 \\
  --output-dir results/cube_over_barrier_current
```

Visualize the replay:

```bash
MUJOCO_GL=glfw python -m morphtamp_x_v2.cli view \\
  --xml results/cube_over_barrier_current/scene.xml \\
  --replay results/cube_over_barrier_current/replay.json \\
  --interactive \\
  --fps 60 \\
  --playback-speed 0.55
```

## Compare grasp candidates

Generate a candidate comparison report and one independent replay per grasp
candidate:

```bash
python -m morphtamp_x_v2.cli compare-grasps \\
  --object plate \\
  --task shelf_place \\
  --panda-xml {PANDA_XML} \\
  --auto-fit-panda \\
  --full-candidate-limit 3 \\
  --position-tolerance 0.05 \\
  --output-dir results/plate_shelf_candidate_comparison
```

Open the report:

```bash
explorer.exe results/plate_shelf_candidate_comparison/candidate_report.html
```

Open the switchable candidate viewer:

```bash
MUJOCO_GL=glfw python -m morphtamp_x_v2.cli browse-candidates \\
  --manifest results/plate_shelf_candidate_comparison/candidate_replays/manifest.json \\
  --fps 60 \\
  --playback-speed 0.55
```

Candidate viewer keys:

- `n` / `d` / `]` / right / up: next candidate
- `p` / `a` / `[` / left / down: previous candidate
- `1`-`9`: jump to candidate
- `r`: replay current candidate
- `h`: help
- `q` / `Esc`: quit

## Interactive object/task browser

Use this when you want to switch tasks and objects without rebuilding commands:

```bash
MUJOCO_GL=glfw python -m morphtamp_x_v2.cli browse \\
  --panda-xml {PANDA_XML} \\
  --auto-fit-panda \\
  --objects cube sphere cylinder plate mug_proxy bowl_proxy capsule tall_box flat_box ring \\
  --tasks tabletop_easy over_barrier narrow_slot shelf_pick shelf_place folded_transfer diagonal_reach_around \\
  --output-dir results/browser_current \\
  --fps 60 \\
  --playback-speed 0.55
```

Object/task browser keys:

- `o`: next object
- `i`: previous object
- `n` / `]` / up: next task
- `p` / `[` / down: previous task
- `r`: replay current case
- `h`: help
- `q` / `Esc`: quit

## Benchmark

```bash
python -m morphtamp_x_v2.cli benchmark \\
  --protocol fixed \\
  --objects cube sphere cylinder plate mug_proxy bowl_proxy \\
  --tasks tabletop_easy over_barrier narrow_slot shelf_pick shelf_place folded_transfer \\
  --panda-xml {PANDA_XML} \\
  --auto-fit-panda \\
  --position-tolerance 0.05 \\
  --full-candidate-limit 2 \\
  --output results/current_object_task_benchmark.json

python -m morphtamp_x_v2.cli analyze-benchmark \\
  --input results/current_object_task_benchmark.json \\
  --output-json results/current_benchmark_summary.json \\
  --output-csv results/current_benchmark_summary.csv \\
  --output-md results/current_benchmark_summary.md
```

The benchmark summary includes:

- `grasp_planning`: coarse/full candidate counts and rejection codes;
- `failure_taxonomy`: task, joint, and grasp failure counts by object/task;
- `task_splits`: development, main, heldout, and unassigned task groups.

Use held-out tasks only after tuning decisions are frozen.

## Morphology benchmark

```bash
python -m morphtamp_x_v2.cli morphology-benchmark \\
  --protocol fixed \\
  --objects cube sphere cylinder plate mug_proxy bowl_proxy \\
  --tasks tabletop_easy over_barrier narrow_slot shelf_pick shelf_place folded_transfer \\
  --panda-xml {PANDA_XML} \\
  --auto-fit-panda \\
  --position-tolerance 0.05 \\
  --full-candidate-limit 2 \\
  --output results/current_morphology_benchmark.json
```

## Continuous morphology optimization

Use this when you want to move beyond the preset design list and search over
segment scales and base placement while enforcing a robust reach margin. For
Panda-aware runs, use `--base-results-cache`; the real Panda IK / Jacobian
base cases are expensive, and the cache makes interrupted runs resumable:

```bash
python -m morphtamp_x_v2.cli optimize-morphology \\
  --protocol heldout_fixed \\
  --panda-xml {PANDA_XML} \\
  --scale-values 0.70 0.82 0.90 1.00 1.10 \\
  --base-x-values 0.00 0.03 0.05 \\
  --minimum-reach-margin 0.05 \\
  --minimum-sigma 0.08 \\
  --maximum-condition-number 30 \\
  --path-cost-weight 0.02 \\
  --base-results-cache results/heldout_panda_base_cache.json \\
  --output results/heldout_panda_singularity_morphology.json
```

Analyze the resulting design trade-offs:

```bash
python -m morphtamp_x_v2.cli design-analysis \\
  --input results/heldout_panda_singularity_morphology.json \\
  --output-json results/heldout_panda_design_analysis.json \\
  --output-md results/heldout_panda_design_analysis.md
```

## Robustness benchmark

Use this after a fixed benchmark passes to test whether the result survives
small pose and obstacle perturbations. Panda-aware robustness is expensive, so
use `--results-cache` for resumable overnight runs. The cache is trial-indexed:
you can run 5 trials first, then rerun with 10 or 20 trials and the completed
rows will be reused as long as the objects, tasks, seed, perturbation settings,
Panda XML, candidate limit, and tolerance stay fixed.

```bash
python -m morphtamp_x_v2.cli robustness-benchmark \\
  --protocol heldout_fixed \\
  --panda-xml {PANDA_XML} \\
  --trials 5 \\
  --seed 42 \\
  --position-noise 0.01 \\
  --obstacle-noise 0.01 \\
  --position-tolerance 0.05 \\
  --full-candidate-limit 1 \\
  --results-cache results/heldout_panda_robustness_full_cache.json \\
  --output results/heldout_panda_robustness_full.json
```

The robustness JSON now contains a report-ready `summary` block with:

- overall success rate and failed-run entries;
- maximum and mean position error;
- minimum and mean Panda Jacobian singular value;
- maximum and mean condition number;
- mean path length;
- by-object and by-task success tables.

## Failure analysis

Turn any benchmark-like JSON containing a `results` list into a compact failure
taxonomy. Static task failures are reported with a `task:` prefix, and Panda /
Franka joint-replay failures are reported with a `joint:` prefix so IK,
collision, singularity, and reach-margin causes do not get mixed together:

```bash
python -m morphtamp_x_v2.cli failure-analysis \\
  --input results/current_morphology_benchmark.json \\
  --output-json results/current_failure_analysis.json \\
  --output-md results/current_failure_analysis.md
```

## Figures

```bash
python -m morphtamp_x_v2.cli visualize-results \\
  --benchmark results/current_object_task_benchmark.json \\
  --morphology results/current_morphology_benchmark.json \\
  --output-dir results/current_figures

explorer.exe results/current_figures/dashboard.html
```

Always check:

```bash
results/current_figures/visualization_manifest.json
```

Look at `data_quality.warnings` before using figures in a report.

## Final evidence and report artifacts

For the current Panda-aware held-out result package, the tracked compact evidence
file is:

```bash
evidence/heldout_panda_final_summary.json
```

The current report-style results chapter is:

```bash
docs/results/panda_heldout_final_report.md
```

The full raw experiment outputs are intentionally kept under the untracked
`results/` directory. When syncing this repository to WSL, exclude only the
root result directory with an anchored rule such as `/results/`; do not use a
bare `results/` exclude, because that can also skip tracked documentation paths
like `docs/results/`.

## Object library

{_object_table()}

## Task library

{_task_table()}

## Morphology design library

{_design_table()}

## Common output files

- `replay.json`: selected plan, static replay frames, and optional Panda joint replay.
- `scene.xml`: generated MuJoCo scene for a replay.
- `candidate_report.html`: visual explanation of candidate ranking.
- `candidate_replays/manifest.json`: switchable candidate replay index.
- `visualization_manifest.json`: figure output manifest and data-quality warnings.

## Troubleshooting

- If interactive rendering fails in WSL, run with `MUJOCO_GL=glfw`.
- If a viewer says `replay JSON does not contain joint_replay`, rerun the command
  with `--panda-xml`.
- If figures look empty, regenerate fresh benchmark JSON with the current code and
  check `data_quality.warnings`.
- If README is stale, run `python tools/update_readme.py`.
"""


def main(argv: list[str] | None = None) -> int:
    cli = argparse.ArgumentParser(description="Update or check generated README.md")
    cli.add_argument("--check", action="store_true", help="check README.md without writing")
    args = cli.parse_args(argv)
    path = ROOT / "README.md"
    content = build_readme()
    if args.check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == content:
            print("README.md is up to date")
            return 0
        print("README.md is stale; run: python tools/update_readme.py")
        return 1
    path.write_text(content, encoding="utf-8")
    print(f"updated {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
