from __future__ import annotations

from pathlib import Path
from typing import Any, Callable
import json
import time

import numpy as np


def _joint_addresses(mujoco: Any, model: Any, joint_names: list[str]) -> np.ndarray:
    addresses = []
    for name in joint_names:
        joint_id = int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, name))
        if joint_id < 0:
            raise ValueError(f"joint {name!r} not found in scene")
        addresses.append(int(model.jnt_qposadr[joint_id]))
    return np.asarray(addresses, dtype=int)


def _gripper_addresses(mujoco: Any, model: Any) -> np.ndarray:
    addresses = []
    for joint_id in range(int(model.njnt)):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, joint_id) or ""
        if "finger" in name.lower() or "gripper" in name.lower():
            addresses.append(int(model.jnt_qposadr[joint_id]))
    return np.asarray(addresses, dtype=int)


def _cube_address(mujoco: Any, model: Any) -> int:
    joint_id = int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "v2_cube_freejoint"))
    if joint_id < 0:
        raise ValueError("v2_cube_freejoint not found in scene")
    return int(model.jnt_qposadr[joint_id])


def _cube_qvel_address(mujoco: Any, model: Any) -> int:
    joint_id = int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "v2_cube_freejoint"))
    if joint_id < 0:
        raise ValueError("v2_cube_freejoint not found in scene")
    return int(model.jnt_dofadr[joint_id])


def _weld_id(mujoco: Any, model: Any) -> int:
    return int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_EQUALITY, "v2_grasp_weld"))


def _mocap_id(mujoco: Any, model: Any, body_name: str = "v2_grasp_anchor") -> int:
    body_id = int(mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name))
    if body_id < 0 or not hasattr(model, "body_mocapid"):
        return -1
    return int(model.body_mocapid[body_id])


def _set_mocap_pose(
    data: Any,
    mocap_id: int,
    *,
    position: list[float] | tuple[float, float, float],
    quat: list[float] | tuple[float, float, float, float] | None = None,
) -> None:
    if mocap_id < 0 or not hasattr(data, "mocap_pos") or not hasattr(data, "mocap_quat"):
        return
    if quat is None:
        quat = [1.0, 0.0, 0.0, 0.0]
    quat_array = np.asarray(quat, dtype=float)
    norm = float(np.linalg.norm(quat_array))
    if norm > 1e-12:
        quat_array = quat_array / norm
    data.mocap_pos[int(mocap_id)] = np.asarray(position, dtype=float)
    data.mocap_quat[int(mocap_id)] = quat_array


def _set_cube(
    data: Any,
    address: int,
    position: list[float],
    qvel_address: int | None = None,
    quat: list[float] | None = None,
) -> None:
    if quat is None:
        quat = [1.0, 0.0, 0.0, 0.0]
    data.qpos[address : address + 7] = np.asarray(
        [position[0], position[1], position[2], quat[0], quat[1], quat[2], quat[3]],
        dtype=float,
    )
    if qvel_address is not None:
        data.qvel[qvel_address : qvel_address + 6] = 0.0


def _set_weld(data: Any, weld_id: int, active: bool) -> None:
    if weld_id >= 0 and hasattr(data, "eq_active"):
        data.eq_active[weld_id] = 1 if active else 0


def _frame_delay(fps: float) -> float:
    fps = float(fps)
    if fps <= 0.0:
        return 0.0
    return 1.0 / fps


def _advance_frame_cursor(cursor: float, *, playback_speed: float, frame_count: int) -> float:
    if frame_count <= 0:
        return 0.0
    speed = max(float(playback_speed), 0.0)
    next_cursor = float(cursor) + speed
    if next_cursor >= float(frame_count):
        return 0.0
    return next_cursor


def _apply_replay_frame(
    data: Any,
    frame: dict[str, Any],
    joint_addr: np.ndarray,
    gripper_addr: np.ndarray,
    cube_addr: int,
    cube_qvel: int | None,
    weld_id: int,
    *,
    enable_visual_weld: bool = True,
    mocap_id: int = -1,
) -> bool:
    """Apply one deterministic visual replay frame.

    The interactive viewer is a kinematic replay display: robot qpos is imposed
    from the planner instead of being generated by MuJoCo actuators. Under that
    playback mode, relying on equality constraints alone can make the carried
    object visually lag behind and then snap to the release pose. Therefore the
    replay's object pose is authoritative every frame; the weld flag is still
    toggled so the scene state matches the grasp/release phase semantics.
    """

    data.qpos[joint_addr] = np.asarray(frame["q"], dtype=float)
    if len(gripper_addr):
        data.qpos[gripper_addr] = float(frame["gripper_width"]) / float(len(gripper_addr))
    _set_cube(
        data,
        cube_addr,
        list(frame["object_position"]),
        cube_qvel,
        quat=list(frame.get("object_quat", [1.0, 0.0, 0.0, 0.0])),
    )
    weld_active = bool(frame["weld_active"])
    if weld_active:
        _set_mocap_pose(
            data,
            mocap_id,
            position=list(frame.get("tcp_position", frame["object_position"])),
            quat=list(frame.get("tcp_quat", frame.get("object_quat", [1.0, 0.0, 0.0, 0.0]))),
        )
    _set_weld(data, weld_id, weld_active and enable_visual_weld)
    return weld_active


def _update_weld_relative_pose(mujoco: Any, model: Any, data: Any, weld_id: int) -> None:
    if weld_id < 0 or not hasattr(model, "eq_data"):
        return
    body1 = int(model.eq_obj1id[weld_id])
    body2 = int(model.eq_obj2id[weld_id])
    rotation1 = np.asarray(data.xmat[body1], dtype=float).reshape(3, 3)
    rotation2 = np.asarray(data.xmat[body2], dtype=float).reshape(3, 3)
    relative_position = rotation1.T @ (
        np.asarray(data.xpos[body2], dtype=float) - np.asarray(data.xpos[body1], dtype=float)
    )
    relative_rotation = rotation1.T @ rotation2
    relative_quat = np.zeros(4, dtype=float)
    mujoco.mju_mat2Quat(relative_quat, relative_rotation.reshape(-1))
    model.eq_data[weld_id, 3:6] = relative_position
    model.eq_data[weld_id, 6:10] = relative_quat


def replay_report(xml_path: str | Path, replay_path: str | Path) -> dict[str, Any]:
    payload = json.loads(Path(replay_path).read_text(encoding="utf-8"))
    joint_replay = payload.get("joint_replay")
    return {
        "schema_version": 1,
        "xml": str(xml_path),
        "replay": str(replay_path),
        "has_joint_replay": joint_replay is not None,
        "frame_count": 0 if joint_replay is None else len(joint_replay.get("frames", ())),
        "success": bool(joint_replay.get("success", False)) if joint_replay else False,
    }


def launch_viewer(
    xml_path: str | Path,
    replay_path: str | Path,
    *,
    fps: float = 60.0,
    playback_speed: float = 0.55,
    key_callback: Callable[[int], None] | None = None,
    stop_requested: Callable[[], bool] | None = None,
) -> None:
    try:
        import mujoco
        import mujoco.viewer
    except ModuleNotFoundError as error:
        raise RuntimeError("viewer requires mujoco") from error
    payload = json.loads(Path(replay_path).read_text(encoding="utf-8"))
    joint_replay = payload.get("joint_replay")
    if not joint_replay:
        raise ValueError("replay JSON does not contain joint_replay; run with --panda-xml first")
    frames = tuple(joint_replay["frames"])
    model = mujoco.MjModel.from_xml_path(str(xml_path))
    data = mujoco.MjData(model)
    joint_addr = _joint_addresses(mujoco, model, list(joint_replay["joint_names"]))
    gripper_addr = _gripper_addresses(mujoco, model)
    cube_addr = _cube_address(mujoco, model)
    cube_qvel = _cube_qvel_address(mujoco, model)
    weld = _weld_id(mujoco, model)
    mocap = _mocap_id(mujoco, model)
    weld_was_active = False
    with mujoco.viewer.launch_passive(model, data, key_callback=key_callback) as viewer:
        print("morphtamp-x-v2 viewer: close window to exit")
        cursor = 0.0
        while viewer.is_running():
            if stop_requested is not None and stop_requested():
                viewer.close()
                break
            frame = frames[int(cursor) % len(frames)]
            weld_active = _apply_replay_frame(
                data,
                frame,
                joint_addr,
                gripper_addr,
                cube_addr,
                cube_qvel,
                weld,
                enable_visual_weld=False,
                mocap_id=mocap,
            )
            mujoco.mj_forward(model, data)
            # Visual replay is kinematic: object qpos from the replay is
            # authoritative every frame. MuJoCo equality welds are still
            # recorded in JSON and used by physics validation, but keeping
            # them active in the passive viewer can fight the imposed object
            # pose and make the carried object visually snap or disappear.
            weld_was_active = weld_active
            viewer.sync()
            cursor = _advance_frame_cursor(cursor, playback_speed=playback_speed, frame_count=len(frames))
            delay = _frame_delay(fps)
            if delay > 0.0:
                time.sleep(delay)
